import image1 from "assets/Device.png";
import image2 from "assets/Cat-energy.png";
import image3 from "assets/Cryptostar.png";

const projects = [
    {
        id: "01",
        title: "Device-32",
        cover: image1,
        alt: "Project-1",
        description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
        GitHub: "https://github.com/Lily-1409/1031015-device-32",
        LiveSite: "https://lily-1409.github.io/1031015-device-32/",
        target: "_blank",
        technology: "HTML / CSS",
    },
    // {
    //     id: "02",
    //     title: "Cat-energy-24",
    //     cover: image2,
    //     alt: "Project-1",
    //     description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
    //     GitHub: "https://github.com/Lily-1409/1031015-cat-energy-24",
    //     LiveSite: "https://lily-1409.github.io/1031015-device-32/",
    //     target: "_blank",
    // },
    // {
    //     id: "03",
    //     title: "Cryptostar",
    //     cover: image3,
    //     alt: "Project-1",
    //     description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
    //     GitHub: "https://github.com/Lily-1409/CryptoStars",
    //     LiveSite: "https://lily-1409.github.io/1031015-device-32/",
    //     target: "_blank",
    // },
    {
        id: "04",
        title: "Drink To Go",
        cover: image3,
        alt: "Project-1",
        description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
        GitHub: "https://github.com/Lily-1409/DrinkToGo",
        LiveSite: "https://lily-1409.github.io/1031015-device-32/",
        target: "_blank",
        technology: "HTML / CSS / JavaScript",
    },
    {
        id: "05",
        title: "Smart Device",
        cover: image2,
        alt: "Project-1",
        description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
        GitHub: "https://github.com/Lily-1409/SmartDevice",
        LiveSite: "https://lily-1409.github.io/1031015-device-32/",
        target: "_blank",
        technology: "HTML / CSS",
    },
    {
        id: "06",
        title: "Antarctica",
        cover: image2,
        alt: "Project-1",
        description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
        GitHub: "https://github.com/Lily-1409/Antarctica",
        LiveSite: "https://lily-1409.github.io/1031015-device-32/",
        target: "_blank",
        technology: "HTML / CSS / JavaScript",
    },
    {
        id: "07",
        title: "Fitness",
        cover: image2,
        alt: "Project-1",
        description: "Выполнение проекта подразумевало освоение базовых понятий для верстки сайта. Основы HTML и CSS: структура HTML документа, работа с тегами, семантическая верстка, работа с изображениями, со стиляим).",
        GitHub: "https://github.com/Lily-1409/Fitness",
        LiveSite: "https://lily-1409.github.io/1031015-device-32/",
        target: "_blank",
        technology: "HTML / CSS / JavaScript",
    },
]

export default projects;